# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7747a691ec9ef6aaf458ee5db446d06559cb0bb3bce26fe38d6bd384490a603b49f4f23b7d073ddbb6aec5e3d3674c35398cba856c3853d562c74d66eb414b79

test:
  secret_key_base: 0bd0d45ed2f6507229ecb7d945feb6a573399ca75eca28378f4d9df9abb075fca4e8a05d1d1ccb26ebe65fb97e5ee4cc6fc9b2277e6a05aaa7907d7968088c6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
